<!doctype html>
<html lang="ja">
<head>
    <!--文字コード指定▼-->
    <meta charset="utf-8">
    <!--IE用コード　旧ブラウザでも最新のバージョンでレンダリング▼-->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!--HPの最大横幅指定、レスポンシブなら「width=device-width」それ以外はページの全体幅を指定▼-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--スマホサイトで「電話」「メールアドレス」にリンクを付けない▼-->
    <meta name="format-detection" content="telephone=no, email=no, address=no">
    <!--【任意】リセットCSS▼-->
    <link rel="stylesheet" href="./css/normalize.css">
    <!--【任意】googleフォントCSS▼-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poiret+One|Jura">
    <!--【任意】アイコンフォントCSS▼-->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css">
    <!--【必須】スタイリング用CSS▼-->
    <link rel="stylesheet" href="./css/contact.css">
    <!--ページタイトル▼-->
    <title>お問い合わせ | テンプレート</title>
</head>

<body>
    <div class="cA">
        <div class="contact_ttl"><h1><i class="fa fa-envelope" aria-hidden="true"></i>&nbsp;お問い合わせ</h1></div>
